### ISSUE TITLE
Server hang on startup

### ISSUE THREAD

**Issue by Vandesdelca32** [phaed420/PreciousStones#742]
After Precious Stones reaches "MySQL connection successful", it hangs the entire server during startup for a full 60 seconds, but not if it's manually reloaded using an external plugin like PlugMan

The plugin reports it's version 9.6.6 in game with /ver

**Comment by adamwbb** [comment]
We are having the same issue right now here is the log output on initial startup:

`28.07 23:11:55 [Server] INFO Enabling PreciousStones v10.5.3
28.07 23:11:55 [Server] INFO Version 10.5.3 loaded
28.07 23:11:55 [Server] INFO MySQL Connection successful
28.07 23:11:55 [Server] INFO Creating table: pstone_cuboids
28.07 23:11:55 [Server] INFO Creating table: pstone_fields
28.07 23:11:55 [Server] INFO Creating table: pstone_unbreakables
28.07 23:11:55 [Server] INFO Creating table: pstone_grief_undo
28.07 23:11:55 [Server] INFO Creating table: pstone_translocations
28.07 23:11:55 [Server] INFO Creating table: pstone_storedblocks
28.07 23:11:55 [Server] INFO Creating table: pstone_players
28.07 23:11:55 [Server] INFO Creating table: pstone_snitches
28.07 23:11:56 [Server] INFO Added new indexes to database
28.07 23:11:56 [Server] INFO Creating table: pstone_purchase_payments
28.07 23:11:56 [Server] ERROR Error at SQL Query: Duplicate key name 'key_grief_locs'
28.07 23:11:56 [Server] ERROR Error at SQL Query: Duplicate key name 'indx_field_owner'
28.07 23:11:56 [Server] ERROR Error at SQL Query: Duplicate key name 'unq_uuid'
28.07 23:11:56 [Server] ERROR Error at SQL Query: Duplicate key name 'inx_player_name'
28.07 23:11:56 [Server] ERROR Error at SQL Query: Duplicate key name 'indx_cuboids_owner'
28.07 23:11:56 [Server] ERROR Error at SQL Query: Duplicate key name 'indx_cuboids_parent'
28.07 23:11:56 [Server] ERROR Error at SQL Query: Duplicate key name 'indx_unbreakables_owner'
28.07 23:11:56 [Server] ERROR Error at SQL Query: Duplicate key name 'indx_storedblocks_1'
28.07 23:11:56 [Server] ERROR Error at SQL Query: Duplicate key name 'indx_storedblocks_2'
28.07 23:11:56 [Server] INFO Added new indexes to database`

and it hangs there until server process is killed

the same issue happens too when using sqlite 

when reloading the server you get this output

`28.07 23:14:42 [Server] INFO Preparing start region for level 2 (Seed: 7826167578441289788)
28.07 23:14:43 [Server] INFO Enabling PreciousStones v10.5.3
28.07 23:14:43 [Server] INFO Version 10.5.3 loaded
28.07 23:14:44 [Server] INFO MySQL Connection successful`

running version 10.5.3 on spigot 1.12
