### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by Test10210410** [phaed420/PreciousStones#776]
I'd like to request a couple of things.

1. If you have 4 protected area's and they are all connected.
Like this
[..][..]
[..][..]

Could it be made so when all those 4 cuboids are from the same owner and connected show the entire area when doing /ps visualize instead of only showing the one you are in.

2. Make the player choose what block to mark / outline the area with. The glass is hard to spot somtimes.

3. Make the player choose the amount of time for the marked area to stay.

Hope this can be added.

Thank you.

**Comment by phaed420** [comment]
Would have to change the structure of visualizations fundamentally.  Not practical at this point.
