### ISSUE TITLE
City Protection is not protecting Armor Stand

### ISSUE THREAD

**Issue by spetznack** [phaed420/PreciousStones#779]
City Protection is not protecting Armor Stands in the latest dev.bukkit version: R: 9.7.1 for 1.8.1 Dec 26, 2014

Verified by attempting to break a item frame in the same protection which the test subject could not.

**Comment by spetznack** [comment]
non-allowed players can also right-click items on a armor stand to pick them up. Any thing I can do about this?

**Comment by adopted3** [comment]
I noticed the same problem... People can grief inside another player's City Protection plot by taking or breaking armor on stands.
