### ISSUE TITLE
Request - Change worlds tp stone

### ISSUE THREAD

**Issue by krustymk** [phaed420/PreciousStones#781]
Is this possible?

Cheers

**Comment by phaed420** [comment]
Whatya mean?

**Comment by krustymk** [comment]
Like a tp stone but it moves you to a different world, like a multiverse portal i guess

**Comment by phaed420** [comment]
You should be able to do with with the existing flags no?  Like with teleport-on-enter.  Just put another pstone in another world and name them both the same.
