### ISSUE TITLE
New Door types and other things...

### ISSUE THREAD

**Issue by NinjaSplat** [phaed420/PreciousStones#789]
For some reason, the new door types added in 1.8 don't lock when I specify them in the "prevent-use" flag. I also recommend changing block IDs to block NAMES since 1.8 removed item IDs. Another thing, ARMOR_STANDS are not protected at all, even when I have the "prevent-item-frame-take" flag enabled from one of your development builds. For feature requests, can you make it possible to add flags such as a "prevent-leaf-decay" flag, a "prevent-fire-spread" flag, and a "prevent-vehicle-place" flag? And can you make it so fires can't be put out by non-allowed players? That would be very helpful if you could do that. :)

**Comment by phaed420** [comment]
Door types now work on newer builds, names can be used instead of ids.
