### ISSUE TITLE
PS Info broken among other things.

### ISSUE THREAD

**Issue by MuroHasegawa** [phaed420/PreciousStones#792]
So doing /ps info yields this error http://pastebin.com/0DQZCtL6

and doing /ps allow or /ps allowall yields this error "Not a valid command or insufficient permissions"

Not sure if its something with the server or just the plugin.

**Comment by phaed420** [comment]
This is weird, I am still unable to reproduce that error.  It works just fine for me.  Can you provide instructions that I can follow to make this happen, starting with a clean server with just PS on it with the default config?

**Comment by MuroHasegawa** [comment]
Absolutely! But its late right now so I will get started on it as soon as I can.

**Comment by MuroHasegawa** [comment]
Okay so using the latest 1.8 Spigot build using Java 8 with 2Gb of ram and latest build of PS. With no changes to the config. Tried with both debug mode on and off. Debug yielded no results.
/ps info works while being in a city protection (Diamond block), but when out of a field it says "Command not recognized".
Error msg for doing /ps info: http://pastebin.com/f4K8SqR2

Doing /ps allow or /ps allowall it says "Not a valid command or insufficient permissions". But doesn't give any errors.
Also it doesn't announce that you have left the field.

**Comment by phaed420** [comment]
What do your permissions look like?

**Comment by MuroHasegawa** [comment]
I am using Essentials groupmanager, the rank Builder is the rank that has all the base perms.
http://pastebin.com/ja1WD4Q8
In my test server I was only using OP to test it out. Will report if I get the same errors with an older version.

**Comment by phaed420** [comment]
Just tested this.  Used GroupManager and added your perms.  Tried both PS 9.7.1 and PS 9.8.0 and everything works fine. Cannot reproduce your error.  One odd thing is that the line numbers in the error output don't match up with the code.  If i were to guess, I'd say that you have multiple versions of PreciousStones.jar in your plugins folder and some old version is loading up by mistake.

**Comment by MuroHasegawa** [comment]
Just looked in my server files. I did forget to remove an old version of PS. Silly me :P. After removing one of the files the commands now work.
Thank you for the help phead420.
