### ISSUE TITLE
where is the price

### ISSUE THREAD

**Issue by dwa1275** [phaed420/PreciousStones#793]
I am trying to set up the price for the p stones, but I can not find the option, I have eco, I have vault, I just cant find this, ive looked for issues, fourms, videos, for hrs today and yesterday, so, How do I set a price so money would be taken from a player when they place a p stone

**Comment by phaed420** [comment]
Here you go: http://preciousstones.shoutwiki.com/wiki/Field_Flag_Reference#price

**Comment by dwa1275** [comment]
so how do I add the flag?? im not new at this but it seems different then the last time I set this up, can you give me an example please

**Comment by phaed420** [comment]
Sure, here you go.  It's a small tutorial on setting up flags:

http://dev.bukkit.org/bukkit-plugins/preciousstones/#w-field-flags

**Comment by phaed420** [comment]
So basically you look in the config under force-fields: and you will see the list of all the configured fields with all their flags.  That is an example of one, the City Protection field. You would add a new flag "price: 100" or something, and then restart the server.

**Comment by dwa1275** [comment]
ok, ive seen that, but do I have to add, Usage: price: 200 or said price to the ps I want players to pay for, I don't see anywhere on here Usage: price:

**Comment by dwa1275** [comment]
so just "Price: amount"

**Comment by phaed420** [comment]
Yep, lowercase tho.

**Comment by dwa1275** [comment]
and what about the p stone I do not want to use, just delete the script for it ???

**Comment by phaed420** [comment]
```
- title: City Protection
  block: 57
  radius: 20
  custom-height: 15
  price: 100
```

**Comment by phaed420** [comment]
Yep, just remove them from that list.

**Comment by dwa1275** [comment]
ok thank you sooooooo, much

**Comment by phaed420** [comment]
Those are just defaults I added in there with random assortment of flags.

**Comment by dwa1275** [comment]
the headache is gone now

**Comment by phaed420** [comment]
No prob ;)

**Comment by dwa1275** [comment]
I don't want to forget, I haven't seen this anywhere, but how do I set the amount of p stones a player can have

**Comment by phaed420** [comment]
sec

**Comment by phaed420** [comment]
There was some vandalism to the flag page, had to revert changes done by anons.  Here is the flag for limits:

http://preciousstones.shoutwiki.com/wiki/Field_Flag_Reference#limits

**Comment by dwa1275** [comment]
ok, cool, im all set, thank agen

**Comment by phaed420** [comment]
Hey btw the new version had visualization bugged.  Upgrade to the latest build from my jenkins to have a good version.
