### ISSUE TITLE
Cast error on DoubleChest

### ISSUE THREAD

**Issue by NathanWolf** [phaed420/PreciousStones#794]
It looks like PreciousStones may have some issues when inspecting double chests?

http://pastebin.com/zuTu9SHv

Caused by: java.lang.ClassCastException: org.bukkit.block.DoubleChest cannot be cast to org.bukkit.block.Chest

**Comment by phaed420** [comment]
This was fixed around build 9.7.3, you're running an old version ;)

**Comment by NathanWolf** [comment]
Oops, thanks! I will update to latest! Sorry for bugging you, love your plugin! :)
