### ISSUE TITLE
[Feature] Mine explode but detroy land OR make no damage

### ISSUE THREAD

**Issue by fastlockel** [phaed420/PreciousStones#796]
Tried the Mine bloc, if you leave everything eplodes like a creeper with many damages and a big hole in the ground.
However some player do not want to have their fields around their base filled with holes like the moon.
Si we protected bloc damages : (with worldguad or with a precious stone bloc). this is working, mine explodes, ground is not destroy but damages to players are 10 or 15x less as before?

**Comment by phaed420** [comment]
You can change the following parameters with the mine:

http://preciousstones.shoutwiki.com/wiki/Field_Flag_Reference#mine
