### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by supawiz6991** [phaed420/PreciousStones#798]
Precious Stones seems to be working okay, however we are getting the following errors:
http://hastebin.com/siwadofana.sm

**Comment by phaed420** [comment]
What version of SimpleClans are you running?

**Comment by phaed420** [comment]
The SQL error there doesn't look like a PS or SC error.  Don't have a table called field list.

**Comment by supawiz6991** [comment]
PreciousStones -version 9.8.3
SimpleClans - version 2.5.1

**Comment by phaed420** [comment]
Yeah Upgrade SC to 2.5.4, that will do it.

**Comment by supawiz6991** [comment]
What about this error: 
[19:53:18] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to PreciousStones v9.8.3
org.bukkit.event.EventException

**Comment by phaed420** [comment]
Yea that's from the bug in SC.  PS tries to get the name of a clan and it bugs out.

**Comment by supawiz6991** [comment]
Cool! I'll give that a shot now

**Comment by supawiz6991** [comment]
Updated sc to 2.5.4 and 99% of the errors except this one:
27.03 21:43:34 [Server] ERROR Error at SQL INSERT Query: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'uuid' in 'field list'

**Comment by phaed420** [comment]
That error isn't from PS or SC.

**Comment by supawiz6991** [comment]
Understood! Thanks for your help!

**Comment by DreamPhreak** [comment]
Thanks phaed420!

**Comment by phaed420** [comment]
No prob :)

**Comment by phaed420** [comment]
Try setting the version in the PS config from 13 to 12 and restart.  This will re-add the uuid column to the pstone_players table.  If its a PS problem that will clear it up.

**Comment by supawiz6991** [comment]
Well done! That seems to have done the trick! The errors were showing up first when people joined and I don't see them now! Woot! tyty!

**Comment by phaed420** [comment]
Great :)
