### ISSUE TITLE
PS is not adding the uuid column to pstone_players by default

### ISSUE THREAD

**Issue by i9hdkill** [phaed420/PreciousStones#800]
When updating from an older Build of PS to Build 478 PS is not creating the uuid column in pstone_players.

Regarding to your code, PS doesn't evencreates the uuid column on a fresh install:
https://github.com/phaed420/PreciousStones/search?utf8=%E2%9C%93&q=pstone_players

I created a Varchar(36) uuid column with Default NULL which is working fine. (PS is adding the user UUID on Login)
But not sure if thats working with namechanges. Does the column needs the "index" value?

**Comment by phaed420** [comment]
Is this happening with SQlite or Mysql?

**Comment by phaed420** [comment]
The index just speeds up the lookups, its not required.
