### ISSUE TITLE
Feeding/repairing spam

### ISSUE THREAD

**Issue by DreamPhreak** [phaed420/PreciousStones#801]
Similar to the default "God Stone", players standing in the field will have their chat filled up with this kind of spam: http://i.imgur.com/4HPH66X.png

For my server, I made the rates really low since the block is pretty overpowered, but still wanted to have it. So I cant raise the repair/heal/feed amount since that wouldn't be fair.

Plus, I havent been able to find any way to turn off this spam. So I'm requesting a command for players to turn off these kinds of messages, like a toggle.

Thank you. (Also congrats on closing so many issues, thats fantastic)

**Comment by phaed420** [comment]
You can turn it off in the config in the warn section.  They look like this slow-repair, fast-damage, air, etc.

**Comment by DreamPhreak** [comment]
Oh yes, I found it. I was wondering what that section was for. Thank you
