### ISSUE TITLE
Cant limit and Huge performance drain!

### ISSUE THREAD

**Issue by deano3663** [phaed420/PreciousStones#805]
Hey love the plugin but have a few major issues.

1. I cant seem to limit the amount of fields people lace , i have tried using both the limits per fields and the global field option but none work , i have done this on a fresh server with just precious stones so it is not a conflict of plugins.
2. Precious stones seems to be using a huge amount of resources when someone places a protection block:
  0.25%	 749.91%	  3.75 s	   374.95 ms	 0.0	       0.0k	    PSBlockListener::onBlockPlace(BlockPlaceEvent)

My other plugins dont use this much all combined 

Please let me know how to do the limit thing though as this is the priority :)

**Comment by deano3663** [comment]
Also could you make it so animals are protected in all fields

**Comment by phaed420** [comment]
Please split these off into 3 separate issues.
