### ISSUE TITLE
Cant limit fields

### ISSUE THREAD

**Issue by deano3663** [phaed420/PreciousStones#806]
I cant seem to limit the amount of fields people lace , i have tried using both the limits per fields and the global field option but none work , i have done this on a fresh server with just precious stones so it is not a conflict of plugins.

**Comment by deano3663** [comment]
Any update on this or is it just my own human error?

**Comment by phaed420** [comment]
No update yet.

**Comment by deano3663** [comment]
Alright cheers

**Comment by phaed420** [comment]
Tested and it works fine.  

Test purpose:  Let only 3 City Protection fields be placed by Member's group.

1. I gave the City Protection the following flag:
```
  limits: [3]
```
2. Then I gave the Members group the limit1 permission.
```
Members:
  preciousstones.limit1: true
```
