### ISSUE TITLE
Huge performace drain

### ISSUE THREAD

**Issue by deano3663** [phaed420/PreciousStones#807]
Precious stones seems to be using a huge amount of resources when someone places a protection block: 0.25% 749.91% 3.75 s 374.95 ms 0.0 0.0k PSBlockListener::onBlockPlace(BlockPlaceEvent)

**Comment by phaed420** [comment]
Gonna add some detailed debug messages with timing info.  Then you can test placing a field on your server, and so I can see where the bottleneck lies.  Stay tuned.

**Comment by deano3663** [comment]
all right awesome :)

**Comment by deano3663** [comment]
Ive changed to the development build and things seemed to of slightly improved

**Comment by phaed420** [comment]
Doubt that helped any.  Most likely its the chunk where the block was placed that made the difference.  Try to track down where it was that block places gave those timings.

**Comment by phaed420** [comment]
Try that out, turn on show-debug-info on the config, and place a field where normally it would take long.  Then paste the results here.

**Comment by deano3663** [comment]
Cant seem to find the actual block that caused the performance issues but it was more of a general performance issue than a spike or specific block /area we updated the server to the latest spigot build  and things have improved in general the even causing the most issues was this one
 PSBlockListener::onBlockPlace(BlockPlaceEvent)

but its minor now not sure if it will increase as more people make claims but i doubt it , i did have the claim as quite large though 
with a radius of 100 and a height of 100 so maybe that affected it?

**Comment by phaed420** [comment]
Size of fields have no bearing on performance.  Maybe it was an area densely populated with fields, or maybe it was interactions between different types like grief-reverts, etc.   Next time you see something funny run the timings to see if we can get a clue.

**Comment by deano3663** [comment]
all right will do was probably an error on my part thanks for all the help and patience :)
