### ISSUE TITLE
animals protect

### ISSUE THREAD

**Issue by deano3663** [phaed420/PreciousStones#808]
Protect animals in fields please

**Comment by phaed420** [comment]
Have you tried the protect-animals flag?  
http://preciousstones.shoutwiki.com/wiki/Field_Flag_Reference#protect-animals

**Comment by deano3663** [comment]
I did try that in the city protection but it didnt seem to work

**Comment by phaed420** [comment]
Tested this as well.

Added the *protect-animals* flag to the City Protection field.  Changed to owner of the field to someone else */ps setowner someoneelse* then tried to kill some chickens, could not.  Everything works fine.

**Comment by phaed420** [comment]
BTW when you add flags to a field on the config.  Those flags will not automatically be added to fields that were placed down previous to the change.  Only new fields placed after you added the flag will have the new flag.
