### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by deano3663** [phaed420/PreciousStones#809]
Whenever the plugin is run with or without being hooked into the mysql database we get this error:
[23:13:10] [Craft Scheduler Thread - 16/ERROR]: Error at SQL INSERT Query: java.sql.SQLException: table pstone_players has no column named uuid

The plugin also causes huge amounts of lag which go away when the server is restarted but will soon come back.

**Comment by phaed420** [comment]
The dev versions should clear that up.

**Comment by deano3663** [comment]
Alright is that available now or are you working on it still?

**Comment by phaed420** [comment]
Pick up the latest promoted version from my Jenkins.  That was fixed a few builds ago.

**Comment by deano3663** [comment]
will do
