### ISSUE TITLE
Permission per stone

### ISSUE THREAD

**Issue by Faller10** [phaed420/PreciousStones#810]
Hi! First of all, nice plugin!
But How can I give my groups acess to just 1 stone?
Is it possible?

Thanks!

**Comment by phaed420** [comment]
You mean one stone per player?

**Comment by phaed420** [comment]
You can use these flags to accomplish those goals:

http://preciousstones.shoutwiki.com/wiki/Field_Flag_Reference#limits
http://preciousstones.shoutwiki.com/wiki/Field_Flag_Reference#required-permission

**Comment by Faller10** [comment]
I mean let a certain group acess one of the configured stones, but not the others!

**Comment by phaed420** [comment]
Here is an example, say you have 2 stones configured on the config.  City Protection, and Entry Bouncer:

You could add this flag to the City Protection:
```
required-permission: city-protection.permission
```
And add this flag to the Entry Bouncer:
```
required-permission: entry-bouncer.permission
```

Then in your permissions setup, add those permission to the groups you want:
```
members:
   city-protection.permission: true
vips:
   entry-bouncer.permission: true
```

**Comment by Faller10** [comment]
Thanks man! REALLY OUTSTANDING WORK!

**Comment by phaed420** [comment]
No prob :)

**Comment by phaed420** [comment]
BTW you can delete the stones that you don't need from the config to get rid of them and only leave the ones you want.  Like you can delete them all and only leave the 1.

**Comment by Faller10** [comment]
Yeah I noticed!
Thanks!
