### ISSUE TITLE
Conflict with essentials [buy] signs

### ISSUE THREAD

**Issue by frizzbee30** [phaed420/PreciousStones#811]
spigot - latest commit
PS stones version 9.8.4 #492 
essentials  v2  build 10

Hi, this is an issue that surfaced about 12 months ago or more, and then resolved following updates to preciousstones. Basically the [buy] signs in essentials are disabled. The first time there was an error relating to placing within a field, non field sign  or similar. It is some time ago.

 We got around this by limiting PS with perworld plugins, making the signs and then re enabling. All has been well until recently. We have now discovered that sometime within the last month, or more, it is no longer possible to place [buy] signs. You can format the sign, but when placed they are blank. If you try to make a PS [buy] sign for a PS field, the same occurs. (rent,share are ok for ps and [sell] for essentials)
Removing PS allows for the essentials [buy] signs to be placed and are functional

I have tried disabling 'use commands for bu'y in the config, just in case that could resolve, but it is still an issue.

No errors are shown in the console and essentials debug shows things progressing normally.

I hope you can advise?  Thanks

**Comment by frizzbee30** [comment]
Hi, you would need to check the share+rent for PS I've loaded into live and I think they may be an issue too, I don't know if this is just because they are broken in the dev version or not etc.

**Comment by phaed420** [comment]
What issue are you guys experiencing with the rent/share?

**Comment by frizzbee30** [comment]
Thank you for fixing the signs issue, you have no idea how much time and trouble you've saved us!!  It really is appreciated.  :)
