### ISSUE TITLE
SQLite Questions

### ISSUE THREAD

**Issue by UnusualToast** [phaed420/PreciousStones#812]
Hi. I'm trying to test and optimize a couple of things on my server, by playing with PreciousStones.db.

Only the pstone_cuboids and pstone_players tables have data in it. pstone_cuboids stores all protection data, as world, location, block, owner, allowed players, last used(?) and flags.

Question: What is pstone_players for? All I see is that it assigns an ID for each players (for some reason that full column is null for me), a last seen (for what?) and some flags which I have no idea what they mean and/or are for, as density:1, 8, 99 or 100 and disabled:true.

I have more than 30k entries in pstone_players, most of them are from players that don't play anymore. Can I drop it without losing any relevant data?

**Comment by phaed420** [comment]
You can drop the players that have the other columns blank without issue.  That table is to store settings for specific players.  Will probably optimize that on the codebase so they are not saved in the first place unless they actually saved a setting.

**Comment by UnusualToast** [comment]
What "other columns"? All players have "id" null and some flags applied (by default, I guess?). What does "density:" means? "disabled"?

![ss 2015-04-05 at 04 30 00](https://cloud.githubusercontent.com/assets/10405276/6998270/0d43f6f4-dbb1-11e4-9b41-9059fe730806.png)

**Comment by phaed420** [comment]
DELETE FROM pstone_players WHERE flags = '{"density":8}'

The last seen column was there for the purging functionality.  But that has been removed in the dev builds, to be added later in a different way.

**Comment by UnusualToast** [comment]
My problem is that since the SQLite file got >15MB, my server started crashing when disabling PreciousStones (server shutdown, /stop). If I try to run it locally, I get http://pastebin.com/ehjQPAVh

Figured that tinkering with the .db might fix it.

**Comment by phaed420** [comment]
Upgrade PS to the latest promoted build on my Jenkins.  That problem was fixed on build 469.
