### ISSUE TITLE
PS still crashing at shutdown.

### ISSUE THREAD

**Issue by UnusualToast** [phaed420/PreciousStones#814]
(Check #812)
PreciousStones still crashes at /stop for me.

"Shutting Down: Saving all pending data..."
Then it timeouts.

I'm using latest from Jenkins, 494

**Comment by phaed420** [comment]
Turn on show-debug-info in the config, then try it again.  It should print out all SQL queries happening.  That should give us a clue.

**Comment by UnusualToast** [comment]
>[Queue] processing 45950 pstone queries...

and countless 

>"UPDATE `pstone_cuboids` SET flags = '{"disabledFlags":["prevent-portal-enter","prevent-portal-destination"]}' WHERE x = -974 AND y = 21 AND z = -1413 AND world = 'world';"

Multicraft seems to be terminating the server after 35s of SQL updates. As I said in #812,

>I tried to run it locally a couple months ago, and it disabled fine. For some reason it didn't/doesn't when ran at any host.

That might explain things a bit. Not sure what to do to fix it atm, but when run locally, it takes <5s to save everything. How much time is the update/saving supposed to take?

**Comment by phaed420** [comment]
Definitely a bug, there shouldn't be 45k dirty stones to save by shutdown time.  I'll look into this.

**Comment by phaed420** [comment]
Can you share your config? You can remove the fields list.  Need to see everything else.

**Comment by UnusualToast** [comment]
debug is off and I left one field. All the other (five) ones are the same, just with different block ID and radius.

http://pastebin.com/ta0563kd

Tell me if you need anything else.

**Comment by phaed420** [comment]
How many records do you have on the pstone_cuboids and pstone_fields tables?

**Comment by UnusualToast** [comment]
(getting data from ~30h old .db)

pstone_cuboids is at ~45k (probably the 45950 that debug showed us)
pstone_fields is clean.

As mentioned in the other ticket,

>Only the pstone_cuboids and pstone_players tables have data in it.

**Comment by phaed420** [comment]
Thanks, narrows it down.

**Comment by phaed420** [comment]
Did you use the enableall or disableall command by any chance?

**Comment by UnusualToast** [comment]
Like, ever? I've been using PS for more than 2 years with the same .db. I do not remember using it, but.. you know, 2 years and a lot of staff.

If you mean during the time between restarts, no, I didn't. The '45950 queries' one was the log for the server that was online for around 10 minutes.

**Comment by phaed420** [comment]
That's what I needed to know.  Thanks.  Can you send me the entire debug output (with debug on) from server start to server shutdown/timeout?  Removing any sensitive info/lines.  Need to track down what happens.

**Comment by UnusualToast** [comment]
Do you need other plugins info aka full start log (aka full plugin list) or only stuff related to PS?

**Comment by phaed420** [comment]
Full start log, then just the PS stuff.

**Comment by UnusualToast** [comment]
Too big for pastebin. [Here, at Gist](https://gist.githubusercontent.com/UnusualToast/fe14f9cd2574df746f70/raw/gistfile1.txt).

**Comment by phaed420** [comment]
Thanks.

**Comment by UnusualToast** [comment]
Huh... http://pastebin.com/XTdmmyVH

Server and all other plugins are disabling fine now, at least PS is not crashing everything, just itself.
